### ISSUE TITLE
Yu'biusk clay not recongizing

### ISSUE THREAD

**Issue by Thefriebster** [ZeroGwafa/ArchMatCounter#10]
Yu'Biusk clay not being reconginzied from the chat box
![clay](https://user-images.githubusercontent.com/63893988/79628405-b6864700-810e-11ea-9c20-e5ef0699e54f.png)

**Comment by ZeroGwafa** [comment]
This is a known issue and I am working on it. Will hope to have an update soon to fix.

**Comment by ZeroGwafa** [comment]
I've updated the chat parser.  Please let me know if this is still an issue.

**Comment by ZeroGwafa** [comment]
I have confirmed that this is working now.
