### ISSUE TITLE
Select Chat

### ISSUE THREAD

**Issue by Multivert** [ZeroGwafa/ArchMatCounter#14]
When selecting ''Chat 0'' it toggles a white box at the bottom left, even if i move my chat box, the white box doesnt follow.  If i put the chat box on the white box, it catches maybe 1/2 - 2/3 of the mats but miss alot ? Any idea why the white box doesnt detect my chat box? thank you

**Comment by ZeroGwafa** [comment]
So, anytime you move your chat windows, you will need to reload the app for it to identify where the windows are on your screen.  Best to set your Runescape UI up the way you want it, then load the app.

I am currently testing a new chat parser right now.  It should be more accurate that it is now.

**Comment by Multivert** [comment]
I reloaded and now it doesnt detect my chat. I have transperancy at the minimum and time stamps

**Comment by Multivert** [comment]
all good, restarted client and now the white box fits my entire chat! really love it :D

**Comment by ZeroGwafa** [comment]
Thanks!
