### ISSUE TITLE
Tracker: Imperial Steel

### ISSUE THREAD

**Issue by forsco** [ZeroGwafa/ArchMatCounter#15]
Imperial Steel is not being recognized by the parser.

Count remains as 0 or whatever amount it is manually set to.

**Comment by ZeroGwafa** [comment]
Please submit all issues in the following format:

Issue:

Options enabled at the time of issue: (Filter, Edit, Goals)

Steps to reproduce issue:

Screenshots

Thanks!

**Comment by ZeroGwafa** [comment]
This seems to be working for me, and others that i've asked.

If you are still having issues, please open a new issue using the format above.

Thanks!
