### ISSUE TITLE
Hopping worlds adds materials to tracker

### ISSUE THREAD

**Issue by amerryma** [ZeroGwafa/ArchMatCounter#16]

**Comment by ZeroGwafa** [comment]
There is nothing I can do about this, it's just the way the chatReader works.  The only thing I can suggest is to stop the tracker when hopping worlds, then starting it again once you're on the new world.

**Comment by amerryma** [comment]
I thought alt1 had some sort of api to detect world changes. Maybe that could be used? @ZeroGwafa
