### ISSUE TITLE
Chatbox text detection broke

### ISSUE THREAD

**Issue by djbrooks111** [ZeroGwafa/ArchMatCounter#19]
Issue: It appears a recent update to the RS3 client changed the font of the chatbox which broke Alt1 chatbox text reading. This issue was resolved by the core Alt1 application, however, since this is a 3rd party app, it must be updated separately. 

Options enabled at the time of issue: (Filter, Edit, Goals) Setup properly

Steps to reproduce issue: Launch app, see that it detects the chatbox, but will not update when a mat is found. This is because of the font change.

Screenshots: (Not needed if you provide reproduction steps).

According to Skillbert, the dev of Alt1, a simple solution is to update the dependencies of the 3rd party to a new version that includes the fixes he added. From his discord: https://discord.com/channels/311312296108359682/353020847511961601/869647833949671476

```
Skillbert
 — 
Today at 2:30 PM
yes the dev of that app needs to update their dependencies (@alt1/chatbox to 0.0.15)
```

**Comment by ZeroGwafa** [comment]
Updated code to use the latest versions.  Thanks!

**Comment by djbrooks111** [comment]
Confirmed fixed, thanks!
