### ISSUE TITLE
suggestion: image recognition on material storage window

### ISSUE THREAD

**Issue by brubsby** [ZeroGwafa/ArchMatCounter#21]
Just found this app and will start to use it, but the data entry for the materials is annoying if a user hasn't been using this since day 1. It would also be helpful if the count gets desynced for any reason, like the other issue about the fortune perk, or materials from research.

**Comment by ZeroGwafa** [comment]
Sorry for not getting back to this sooner!  Was on break from RS for IRL stuff.

I've considered this, but it would take a substantial re-write of the app, which unfortunately, is not on my priority list.

Perhaps with the potential of an official client API, this will be something easier to accomplish.
