### ISSUE TITLE
Some Materials not registering.

### ISSUE THREAD

**Issue by Ironsnake-iron** [ZeroGwafa/ArchMatCounter#24]
Hello! I've noticed in my recent push through archaeology that both the Hellfire Metal, and Yu'biusk clay don't get added to the material list as I am excavating them. All other Materials seem to show up exactly as intended. With the Yu'biusk clay, it would flash on the screen showing that I got the material, but the quantity wouldn't go up in the app, but with the Hellfire Metal it isn't recognizing that I am getting it at all. Could you look into this for me? Thank you!

**Comment by Ironsnake-iron** [comment]
Also, I've tried Factory Resetting the app as well. I had the filter selected just for the materials at Hellfire Forge As I set everything else to 0 when I move on to a new digsite. Thank you!

**Comment by Ironsnake-iron** [comment]
https://www.dropbox.com/s/9rtuiazdd41yfyn/ArchMatCounter%20Problem.mp4?st=k9ca6cli&dl=0

Here is a Dropbox link to the video showing exactly the issue. All materials accounted for aside from Hellfire Metal.

**Comment by ZeroGwafa** [comment]
Apologies!  I've got a couple of major fixes on the way (Had to do a bit of re-design to make adding future mats/artefacts easier).  Possibly out by end of this week, as I have some IRL stuff that takes priority.

**Comment by ZeroGwafa** [comment]
Fixed :-) https://github.com/ZeroGwafa/ArchMatCounter/commit/d5260cc7da25b156dddf6cc3f9935cb2fc9b8e3d

**Comment by Ironsnake-iron** [comment]
I appreciate you making the time to look into and fix this even with real life stuff going on! That always takes priority! 

I appreciate you and all that you do. This Alt1 app has changed my life in terms of archaeology. It made a skill that I wasn't fond of actually bearable again. Thank you again!!
