### ISSUE TITLE
Edit goal cell on double click

### ISSUE THREAD

**Issue by krissrex** [ZeroGwafa/ArchMatCounter#3]
Nice app! What do you think about adding this feature?  

Editing goals with double click would make it easier than: expanding menu, then toggling edit, then editing, then disable edit, and finally close the menu.

**Comment by ZeroGwafa** [comment]
I think I can make this happen.  Hang tight!

**Comment by ZeroGwafa** [comment]
Acutally, I'll hold off on this.  I have an Artifact calculator baked into the next release.

**Comment by ZeroGwafa** [comment]
Artifact calculator has been released.  Check the readme for details.
