### ISSUE TITLE
Change Clear Qty and Goals button text to "Clear Qty" and "Clear boals"

### ISSUE THREAD

**Issue by krissrex** [ZeroGwafa/ArchMatCounter#4]
**Description:** In the menu, you have 2 buttons to clear column data. 
The button labels are "Qty" and "Goals". When the alt1 window is narrow, the "Goals" button flows down to the line below. This makes it unclear what the "Goals" button does, because it is no longer close to the "Clear" text, making them seem unrelated. Renaming the buttons and removing the "Clear:" label would simplify this case. You already did it with "Export data as CSV".

**Actual:**  A "Clear: " section in Menu with "Qty" and "Goals" buttons.
![image](https://user-images.githubusercontent.com/7364831/78611381-21aa6080-7867-11ea-9d26-117b0dc60aa8.png)

**Expected:** A "Clear Qty" and "Clear goals" button. No "Clear:" label. Buttons can be aligned on the same line or centered and in a vertical direction, aligning with the export-button.

**Comment by ZeroGwafa** [comment]
The menu is due for a do-over.  Learned a couple new things about Alt1 recently.

**Comment by ZeroGwafa** [comment]
I've changed the text on the buttons until a menu re-write can be finished.
