### ISSUE TITLE
Auto-screener & imp-souled tool don't count

### ISSUE THREAD

**Issue by blakenerdway** [ZeroGwafa/ArchMatCounter#6]
I'm assuming this occurs whenever more than 1 text pops up on the chat box at a time (maybe not), but the plugin doesn't count materials that are teleported using the imp-souled perk.

Also doesn't seem to work whenever your auto-screener spits out something and a porter (or imp-souled perk) teleports it to the bank.

**Comment by ZeroGwafa** [comment]
AFAIK, imp-souled doesn't tell you which material was teleported away?  If it does, could you provide a screenshot, and I will develop a fix.

Yup, I just got access to the auto screener, and a fix is in the works.  Probably out within the next day.

**Comment by blakenerdway** [comment]
You're right that the imp-souled won't tell you. Too bad about that one! Look forward to the update on auto screener. How will we need to update it once you've pushed a fix?

**Comment by ZeroGwafa** [comment]
The app will auto-update when you load it, after I push an update.

I may look into having a popup for when this happens for visual confirmation.

**Comment by ZeroGwafa** [comment]
Auto Screener + Porter interaction fix has been pushed,

Closing issue, Thanks!
