### ISSUE TITLE
Highlight/Filter non achieved goals

### ISSUE THREAD

**Issue by jordan30001** [ZeroGwafa/ArchMatCounter#7]
Would it be possible to highlight non achieved goals in red.

Or filter out all rows that do not have a goal or have been achieved?

**Comment by ZeroGwafa** [comment]
Sorry, my PC needs repairs and I won't be able to get to this for a bit.  Hopefully parts come in Tuesday.

**Comment by ZeroGwafa** [comment]
I have adjusted the logic to check if the goals are enabled,  It will now show only rows where a goal is set.  Highlighting remains the same.  No addition highlighting for unfulfilled goals will be added, since all other rows (Where qty = 0, or hide checkbox is checked) will be shown.
